services:
  db:
    image: postgres:12.4
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: grinandrey/yamdb_final:latest
    container_name: web
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
